# Generated by Django 4.2.20 on 2025-05-31 09:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("village", models.CharField(max_length=200)),
                ("city", models.CharField(blank=True, max_length=200)),
                ("address", models.CharField(max_length=500)),
                ("phone", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(default="fallback.png", upload_to="uploads/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique ID for this animal",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("breed", models.CharField(max_length=200)),
                ("age", models.CharField(max_length=2)),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "Male"), ("f", "Female")],
                        default="m",
                        max_length=1,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="Bhatta Chowk, Rawalpindi", max_length=100
                    ),
                ),
                ("quoted_price", models.CharField(max_length=7)),
                ("defects", models.CharField(blank=True, default="No", max_length=300)),
                ("teeth", models.CharField(max_length=10)),
                ("weight", models.CharField(blank=True, default="1", max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("b", "Bakra"),
                            ("d", "Dumba"),
                            ("v", "Vehra"),
                            ("c", "Camel"),
                        ],
                        default="b",
                        max_length=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("s", "Sold"),
                            ("a", "Available"),
                            ("u", "Unavailable"),
                        ],
                        default="a",
                        max_length=1,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animals.owner"
                    ),
                ),
            ],
        ),
    ]
