# Generated by Django 4.2.20 on 2025-05-31 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0003_alter_animal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="create_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animal",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
